const {
    RichEmbed
} = require('discord.js')
module.exports = {
    name: 'compliment',
    description: 'Returns mentioned users compliment.',
    execute(msg, client, args) {
        let user = msg.mentions.users.first()
        if (!user) user = msg.author
        let replies = [
            "I'd shag you for a fiver",
            "I want you to marry my daughter",
            "this is the wettest I've ever been.",
            "you have beautiful eyes.",
            "I'd shag you for a fiver",
            "I want you to marry my daughter",
            "this is the wettest I've ever been.",
            "you're amazing",
            "it's nice to see you (:",
            "your face is perfect",
            "your hair looks like ocean waves",
            "looking good!",
            "damn your a fucking beautiful person....I want you to fuck me",
            "you've got a nice laugh.",
            "you're a big hunky slab of sex.",
            "I've ever felt more accepted and respected in my life.",
            "you're a living wholesome meme",
            "you're my best friend",
            "your face is perfect",
            "you've got a nice laugh.",
            "you're a big hunky slab of sex",
            "I've ever felt more accepted and respected in my life.",
            "damn your a fucking beautiful person....I want you to fuck me",
            "you're my best friend",
            "this is the wettest I've ever been.",
            "you're a living wholesome meme",
            "you're my best friend",
            "you have beautiful eyes.",
            "you're my best friend",
            "you don't look like someone who studies Computer Science",
            "you are the one drop of brightness in an otherwise dreary world",
            "you're amazing",
            "your face is perfect",
            "there are two types of friends in this world. Friends you can have a beer with, and friends who can marry your sister. My sister is available. Just sayin'",
            "out of everyone I know, you were the only person I could think of who could raise my son better than me.",
            "I hope my kid will grow up to be like you.",
            "out of everyone I know, you were the only person I could think of who could raise my son better than me.",
            "I'll give 1 million camels for you!",
            "your face is perfect",
            "I hope my kid will grow up to be like you",
            "you are the one drop of brightness in an otherwise dreary world",
            "you look great today!",
            "you're amazing",
            "your face is perfect",
            " you're a living wholesome meme",
            "your hair looks like ocean waves",
            "looking good!",
            "you're amazing",
            "your face is perfect",
            "thanks for being there for me.",
            "you could have a career as a phone sex line operator",
            "I'd shag you for a fiver",
            "you don't look like someone who studies Computer Science",
            "you've got a nice laugh.",
            "damn your a fucking beautiful person....I want you to fuck me",
             "thanks for being there for me.",
            "that's a really clever username!",
            "you have beautiful eyes.",
            "it's nice to see you (:",
            "I'll give 1 million camels for you!",
            " your face is perfect",
            "I'd shag you for a fiver",
            " I'd shag you for a fiver",
            "I've ever felt more accepted and respected in my life.",
            "you don't look like someone who studies Computer Science",
            "Worked",
            "I'm sure she would love knowing that!",
            "Think your ass needs some tongue :tongue:",
            "First, I�d bend you over and see if the back is as magnificent as the front!",
            "I'd ram home. My fantasy",
            "me too ;)",
            "I�m aiming for the butthole ma�am",
            "Mine as well",
            "I dunno what�s better, thighs or hips.",
            "So am I...I'd love to play. Please post more",
            "I mean YUM....but addicted to what?",
            "Would have to give the butthole a try",
            "I want to bounce on it",
            "Think your ass needs some tongue :tongue:",
            "Unzips....again",
            "Mine as well",
            "I'd ram home. My fantasy",
            "I'm sure she would love knowing that!",
            "I want to bounce on it",
            "And I'll drink every delicious drop!:yum::smiling_face_with_3_hearts:",
            "Thank you so much &lt;3",
            "Yup",
            "I am now",
            "Yum",
            "You definitely can, but I can't guarantee a comfortable ride :face_with_hand_over_mouth::smirk:",
            "me too ;)",
            "Amazing booty. Would love to see more of these.",
            "Yes :smiling_imp::smiling_imp:",
            "There's worse addictions ;)",
            "Damn girl, you�ve have such a sexy body:relaxed:",
            "I would love to",
            "I remember this from an old comedian. His answer was �depends on which direction she is facing�",
            "And what do you want in return?",
            "Oh yes",
            "What happened to user Eveninginparis? Just saw her profile today and loved it. Been posting for like a month and an hour later she deleted her account. Hope she didn't get doxed or something.",
            "Gorgeous body",
            "You wont get cleaner;)",
            "Tell her. She is gorgeous!",
            "Is there anything you wouldn�t do with me? Tommy, do you have a line?",
            "Your gonna need to take of the bra and jeans, otherwise your hot body will have tan lines!",
            "Most definitely!",
            "That ass is addictive",
            "If by love you mean lick then and tease them until you're moaning for more then yes, they absolutely can.",
            "I would love to",
            "Amazing booty. Would love to see more of these.",
            "I guess I hopped on Reddit at the right time :wink:",
            ":astonished: thonggobbler :fire::peach:",
            "I wanna be your skirt and wear me",
            "Holy tits, Batman :heart_eyes::heart_eyes::heart_eyes::drooling_face:",
            "Ok, this may be the one that r/ShinyClits would really love! :heart:",
            "How do we feel about spreading those cheeks next time?",
            "Come here bitch and lets see if you can really take it like you say",
            "I'd be in, then out, then in and repeat until you know when....:wink:",
            "See through yoga pants in a provocative position :)",
            "*raises hand and erection",
            "You do know it is going in your butt right:smiling_imp:?",
            "Those tits :drooling_face::heart_eyes:",
            "Love it! So hot!",
            "Like I'd do anything to cum inside",
            "Very nice",
            "Hi /u/Lrl15 - mod here - Please  do a verification post to help confirm this is you.",
            "I'd be in, then out, then in and repeat until you know when....:wink:",
            "Come here bitch and lets see if you can really take it like you say",
            "Keep it coming... Love it :heart_eyes::kiss::kissing_heart:",
        ]

        let random = Math.floor(Math.random() * replies.length)

        let embed = new RichEmbed()
            .setTitle(`Compliment machine`)
            .setDescription(`${user.tag}, \n${replies[random]}`)
            .setColor("RANDOM")

        msg.channel.send(embed)
    }
}