const {
    RichEmbed
} = require('discord.js')
module.exports = {
    name: 'insult',
    description: 'Returns mentioned users insult.',
    execute(msg, client, args) {
        let user = msg.mentions.users.first()
        if (!user) user = msg.author
        let replies = [
            "What the fuck did you just fucking say about me, you little bitch? I’ll have you know I graduated top of my class on the discord bots list, and I’ve been involved in numerous secret guilds with Al-Quaeda, and I have over 300 confirmed commands. I am trained in computer vision and I’m the top bot in the entire discord forces. You are nothing to me but just another target. I will wipe you the fuck out with precision the likes of which has never been seen before on this server, mark my fucking words. You think you can get away with saying that shit to me because I'm a bot? Think again, fucker. As we speak I am contacting my secret network of raiders across discord and your IP is being traced right now so you better prepare for the storm, maggot. The storm that wipes out the pathetic little thing you call your life. You’re fucking dead, kid. I can be anywhere, anytime, and I can ban you in over seven hundred ways, and that’s just with my core modules. Not only am I extensively trained in porn suggestions, but I have access to the entire arsenal of urban dictionary and I will use it to its full extent to wipe your miserable ass off the face of the continent, you little shit. If only you could have known what unholy retribution your little “clever” command was about to bring down upon you, maybe you would have insulted somebody else. But you couldn’t, you didn’t, and now you’re paying the price, you goddamn idiot. I will shit fury all over you and you will drown in it. You’re fucking dead, kiddo.",
            "I don't like you. I don't like anybody who has as little respect for others as you do. Go away, you swine. You're a putrescent mass, a walking vomit. You are a spineless little worm deserving nothing but the profoundest contempt. You are a jerk, a cad, and a weasel. Your life is a monument to stupidity. You are a stench, a revulsion, a big suck on a sour lemon. You are a curdled staggering mutant dwarf smeared richly with the effluvia and offal accompanying your alleged birth into this world. Meaningful to no one, abandoned by the puke-drooling, giggling beasts that sired you and then killed themselves in recognition of what they had done.",
            "you're a real cunt, you know that?",
            "i mock your value system, you also appear foolish in the eyes of others",
            "your gene pool needs a little chlorine",
            "I'd challenge you to a battle of wits, but I see you're unarmed.",
            "you have nothing to say, and Godwin's Law does not apply when writing about you. You are the anti-Midas, for all that you touch becomes valueless and unusable. Mothers gather their children close when you appear. You are an aberration, a corruption, and a boil that needs to be lanced. You are a poison in need of being vomited. You are a tooth so rotten it infects the whole body. You are sperm that should have been captured in a condom and flushed down a toilet.",
            "you make blind kids cry why don't you slip into something more comfortable... like a coma.",
            "you're the poundland version of your father",
            "you must've been born on a highway, that's where most accidents happen.",
            "your mother fucks for bricks, so she can build your sister a whore house",
            "make like your hairline and recede",
            "why are you playing so hard to get when you're already hard to want",
            "your mother prayed for a miscarriage.",
            "you fight like a dairy farmer",
            "I wouldn't fuck you for practice",
            "your face makes me laugh",
            "God ruined a perfectly good asshole when he put teeth in your mouth.",
            "you are impossible to underestimate.",
            "you must've been born on a highway, that's where most accidents happen.",
            "your mum should've swallowed.",
            "you are a pizza burn on the roof of the world's mouth.",
            "anyone who ever loved you was wrong.",
            "it would be easier for me to count your brain cells than your rolls of fat.",
            "Im so glad your dad beat you instead of cancer.",
            "Your mom has seen more black cock than a KFC urinal.",
            "you swine. You vulgar little maggot. You worthless bag of filth. I wager you couldn't empty a boot of excrement were the instructions on the heel. You are a canker. A sore that won't go away. I would rather kiss a lawyer than be seen with you. Try to edit your responses of unnecessary material before attempting to impress us with your insight. The evidence that you are a nincompoop will still be available to readers, but they will be able to access it more rapidly.",
            "you are one of those people who would be enormously improved by death.",
            "You're like an insect. You're small, you're insignificant, you're worthless, you won't make a difference to my life, but goddamn do I want to get rid of you.",
            "It would be easier for me to count your brain cells than your rolls of fat",
            "You're like an insect. You're small, you're insignificant, you're worthless, you won't make a difference to my life, but goddamn do I want to get rid of you.",
            "Listen here you toe-eyed cabbage, I wasn't born into this world so your fat ass could choke out low level insults at me. I hope you stub your toe in the dark and have to crawl around your bedroom at 3:47am in the horrific pain after going to the kitchen for a midnight snack of cheese and crackers you absolute gormless minger",
            "your birth certificate is an apology from the condom factory.",
            "there's no u in teem",
            "you're like the top piece of bread. Everybody touches you, but nobody wants you.",
            "You're as weak as the two pathetic pelvic thrusts that made you",
            "Does your asshole ever get jealous of all the shit that comes out of your mouth",
            "I'd rather hear gunshots coming from my parents' room than hear you speak again.",
            "you're like an insect. You're small, you're insignificant, you're worthless, you won't make a difference to my life, but goddamn do I want to get rid of you.",
            "you're a pathetic, shallow pile of poorly hidden insecurities",
            "you are a pizza burn on the roof of the world's mouth.",
            "I'm not saying that you're a slut, but your spit would be accepted at a sperm bank.",
            "Did you know your dad was a magician? The moment he heard the word pregnancy, he just disappeared.",
            "I hope you out live your children you pathetic fuck.",
            "You look like a bag of smashed assholes",
            "you fight like a dairy farmer",
            "suck my fucking dick bitch",
            "you have the sexual charisma of a toddler's wake",
            "If I had to commit suicide I'd jump of your ego and land on your IQ.",
            "no wonder you look so black, so you said advance fucked you huh",
            "You half-witted, scruffy-looking nerf herder!",
            "You're the reason abortion (or euthanasia) should be legalized",
            "you're not being the person Mister Rogers believed you could be.",
            "everyone just tolerates you.",
            "you make blind kids cry why don't you slip into something more comfortable... like a coma.",
            "I'm not saying you're fat, but you look like someone poured you into your clothes and you forgot to say when.",
            "your mother was a hamster and your father smelt of elderberries,",
            "you fucking idiot, you total fucking idiot. That was your job you fucking moron, you cretin. You're a fuckhead, that's what you are. A fucking shithead.",
            "is your family tree a straight line?",
            "you are wholly without any redeeming social grace or value. If God ever decides to give the planet an enema you'd better run like the wind because anywhere you stand is a suitable place for The Insertion. There is no animal so disgusting, so vile that it deserves comparison to you, for even the lowest, dirtiest, most parasitic member of the animal kingdom fills an ecological niche. You fill no niche. To call you a parasite would be injurious and defamatory to the thousands of honest parasitic species. You are worse than vermin, for vermin do not pretend to be what it is not. You are truly human garbage. You are a fraudulent, lying, predatory charlatan. You are of less worth than a burnt-out light bulb. You will forever live in shame.",
            "it would be easier for me to count your brain cells than your rolls of fat.",
            "you're a complete tool but not half as useful",
            "Thou Foul Lump Of Deformity",
            "What Are You Gonna Do for a Face when the Baboon Wants It's Butt Back?",
            "Go Sit on a Pine Cone",
            "Don't you have a terribly empty feeling - in your skull?",
            "Your mind is on vacation but your mouth is working overtime.",
            "If your gonna be two faced, honey at least make one of them pretty.",
            "Keep talking...I'm diagnosing you.",
            "I can only please one person a day. Today isn't your day. Tomorrow isn't looking good either.",
            "Keep talking, someday you'll say something intelligent!",
            "I Fart in Your General Direction",
            "You're so ugly, you scared the crap out of the toilet.",
            "I'd like to help you out. Which way did you come in?",
            "You are so old, when you were a kid rainbows were black and white.",
            "You're like Monday mornings, nobody likes you.",
            "Stupidity is not a crime so you are free to go.",
            "If I had a face like yours, I'd sue my parents.",
            "You're so fat, you leave footprints in concrete.",
            "May you always step on a wet spot after putting on fresh socks.",
            "I can lose weight, but you'll always be ugly.",
            "You're not pretty enough to be that stupid.",
            "You're as Sharp as a Marble",
            "You get ten times more girls than me? ten times zero is zero...",
            "I don't know what your problem is, but I'll bet it's hard to pronounce.",
            "Here's a tissue, you have a little piece of sh*t on your lips.",
            "If There Was an Award for Laziness, You'd Need Someone to Pick It Up for You",
            "Pew! Pew! Pew!' That's the sound of me deflecting your whiny b*tching with my happiness shield.",
            "Now I know why everyone talks about you behind your back.",
            "You shouldn't act hard-to-get when you're already hard-to-like.",
            "If you really spoke your mind, you'd be speechless.",
            "Some babies were dropped on their heads but you were clearly thrown at a wall.",
            "Ever since I saw you in your family tree, I've wanted to cut it down.",
            "If I Were a Bird, You Would be the First Person I'd Poop on",
            "You, sir, are an oxygen thief!",
            "I would like to leave you with one thought, but I'm not sure if you have anywhere to store it in.",
            "I'd slap you, but that would be animal abuse.",
            "Wipe your mouth, there's still a tiny bit of bullshit around your lips.",
            "Roses Are Red. Violets Are Blue. You Look Like a Monkey and Belong in a Zoo. Do Not Worry, I'll be There Too. Not in the Cage, but Laughing at You.",
            "I'm jealous of people that don't know you!",
            "You Stuck-up, Half-witted, Scruffy-looking Nerfherder!",
            "I will ignore you so hard you will start doubting your existence.",
            "You must have been born on a highway because that's where most accidents happen.",
            "You're so dumb that you got hit by a parked car.",
            "I don't understand your specific kind of 'stupidity,' but I do admire your total commitment to it.",
            "I don't know what makes you so stupid, but it really works.",
            "You're like the end pieces of a loaf of bread. Everyone touches you, but nobody wants you.",
            "If ugly were a crime, you'd get a life sentence.",
            "All day I thought of you... I was at the zoo.",
            "If I told you that I have a piece of dirt in my eye, would you move?",
            "Why don't you go play in traffic.",
            "Why don't you slip into something more comfortable... like a coma.",
            "I'd love to kill you with kindness, but all I have is this chainsaw.",
            "You fear success, but you really have nothing to worry about.",
            "Roses are red violets are blue, God made me pretty, what happened to you?",
            "Your family tree must be a cactus because everybody on it is a prick.",
            "May your life be as pleasant as you are.",
            "How old are you? - Wait I shouldn't ask, you can't count that high.",
            "So, a thought crossed your mind? Must have been a long and lonely journey.",
            "You're as Useful as a White Crayon",
            "You're Nuttier then a Squirrel's Turd",
            "Someone Getting Drunk and Taping Crayons to Their Feet Could Write Better Than You",
            "I've met several pricks before, but you sir are a cactus.",
            "Whenever I see you, middle finger gets an erection.",
            "As an outsider, what do you think of the human race?",
            "I have neither the time nor the crayons to explain this to you.",
            "May the Fleas of a Thousand Camels Infest Your Armpits",
            "Don't feel bad. A lot of people have no talent.",
            "I may not be perfect, but at least I'm not you.",
            "Who ate your bowl of sunshine this morning, thundercloud?",
            "If I wanted to kill myself I'd climb your ego and jump to your IQ.",
            "I Know Five Fat People and You're Two of Them",
            "Keep rolling your eyes, perhaps you'll find a brain back there.",
            "I can explain it to you, but I can't understand it for you.",
            "Somewhere out there, there's a tree working very hard to produce oxygen so that you can breathe. I think you should go and apologize to it.",
            "I Could Carve a Better Man out of a Banana",
            "No I'm not insulting you, I'm describing you.",
            "You are about to exceed the limits of my medication.",
            "Look at the time, it's time for you to shut the f*ck up!",
            "Brains aren't everything. In your case they're nothing.",
            "Awww...my middle finger likes you.",
            "Of course I talk like an idiot, how else would you understand me?",
            "Have you been shopping lately? They're selling lives, you should go get one.",
            "Your face is just fine, but you'll have to put a bag over that personality.",
            "Your birth certificate is an apology letter from the condom factory.",
            "If you ran like your mouth, you'd be in good shape.",
            "Your house is so dirty you have to wipe your feet before you go outside.",
            "Im busy now. Can I ignore you some other time?",
            "Sometimes, I wish I was deaf so your grammar wouldn't bother me so much.",
            "You're so ugly, when your mom dropped you off at school she got a fine for littering.",
            "You Lewd, Crude, Rude, Bag of Pre-chewed Food Dude",
            "I'm sorry, was that meant to offend me? The only thing offending me right now though is your face.",
            "ABRACADABRA! Nope, you're still a b*tch.",
            "Are you afraid that zombies will eat your brain? Nah, you'll be fine.",
            "If laughter is the best medicine, your face must be curing the world.",
            "Feed your own ego. I'm busy.",
            "Pardon me, but you've obviously mistaken me for someone who gives a damn.",
            "How did you get here? Did someone leave your cage open?",
            "You so dumb, you think Cheerios are doughnut seeds.",
            "You're Like a Russian Doll - Full of Yourself",
            "Don't you need a license to be that ugly?",
            "My alone time is meant for your safety.",
            "You are so old, your birth-certificate expired.",
            "Every time I'm next to you, I get a fierce desire to be alone.",
            "You couldn't handle me even if I came with instructions.",
            "Just because you have one doesn't mean you have to act like one.",
            "I guess you prove that even god makes mistakes sometimes.",
            "If you spoke your mind, you'd be speechless.",
            "You need a kiss...on the neck...from a crocodile.",
            "I'm busy, you're ugly. Have a nice day.",
            "If You Were Half as Smart as You Think You Are, You'd be Twice as Smart as You Really Are",
            "I love the sound you make when you shut up.",
            "If you're going to act like a turd, go lay on the yard.",
            "Mall Slut",
            "I'm not saying I hate you, but I would unplug your life support to charge my phone.",
            "Behind every fat woman there is a beautiful woman. No seriously, your in the way.",
            "We can always tell when you are lying. Your lips move.",
            "Fart-Knocking Ding-Dong",
            "The only way you'll ever get laid is if you crawl up a chicken's ass and wait.",
            "Okay, let me file what you just said under 'I couldn't care less'.",
            "Calling you an idiot would be an insult to all the stupid people.",
            "You look like something that came out of a slow cooker.",
            "You have Diarrhea of the mouth; constipation of the ideas.",
            "Know your role, shut your hole!",
            "Stop trying to be a smart ass, you're just an ass.",
            "Please shut your mouth when you're talking to me.",
            "If I Throw a Stick Will You Leave?",
            "Mushroom infected pitbull foreskin",
            "You're the reason the gene pool needs a lifeguard.",
            "Sure, I've seen people like you before - but I had to pay an admission.",
            "Here, let me wash the stupid right off of you. Oh wait, it's not coming off.",
            "If I had a dollar for every brain you don't have, I'd have a dollar.",
            "Just because I'm smiling doesn't mean I don't want to hit you in the face.",
            "Shock me, say something intelligent.",
            "Let's go to the zoo. I've always wanted to meet your family.",
            "The last time I saw something like you, I flushed it.",
            "You're so fake, Barbie is jealous.",
            "You have a Face like a Bulldog Chewing a Wasp",
            "I'd like to see things from your point of view but I can't seem to get my head that far up my ass.",
            "Geekburger with Cheese",
            "Since narcissistic is such a big word for you, how about asshole? You know what an asshole is, right?",
            "Are you always this stupid or is today a special occasion?",
            "Mind if I ask where the OFF button for your mouth is?",
            "In order to insult me, I must first value your opinion. Nice try though.",
            "Is Your Butt Jealous of the Amount of Crap That Just Spewed out of Your Mouth?",
            "Don't like my sarcasm, well I don't like your stupid.",
            "Awww...it's cute when you try to talk about things you don't understand.",
            "You are not as bad as people say, you are much, much worse.",
            "There is no vaccine against stupidity.",
            "You look like a 'before' picture.",
            "Please cancel my subscription to your issues.",
            "I'm sorry for hurting your feelings, I thought you already knew you were stupid.",
            "They say opposites attract. I hope you meet someone who is good-looking, intelligent, and cultured.",
            "I'm sorry I didn't get that. I don't speak bullsh*t.",
            "There's no need to repeat yourself. I ignored you the first time.",
            "It's better to let someone think you are an Idiot than to open your mouth and prove it.",
        ]

        let random = Math.floor(Math.random() * replies.length)

        let embed = new RichEmbed()
            .setTitle(`Insult machine`)
            .setDescription(`${user.tag}, \n${replies[random]}`)
            .setColor("RANDOM")

        msg.channel.send(embed)
    }
}